version: "3.9"
x-build: &build
  build: .
x-env: &env
  environment:
    - PORT=${PORT}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - S3_BUCKET=${S3_BUCKET}
    - SENTRY_DSN=${SENTRY_DSN}
x-test: &test
  volumes:
    - ./test-results:/app/test-results
  profiles:
    - testing
services:
  web:
    <<: [*build, *env]
    ports:
      - ${PORT}:${PORT}
  test:
    <<: [*build, *env, *test]
    command: pytest /app/src/test/test.py