version: "3.9"
x-build: &build
  build: .
x-env: &env
  environment:
    - PORT=${PORT}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - S3_BUCKET=${S3_BUCKET}
x-test: &test
  volumes:
    - ./src/tests/custom/results:/app/src/tests/custom/results
    - ./src/tests/main/results:/app/src/tests/main/results
  profiles:
    - testing
services:
  web:
    <<: *build
    <<: *env
    command: python /app/src/app.py
    ports:
      - ${PORT}:${PORT}
  test:
    <<: *build
    <<: *env
    <<: *test
    command: pytest /app/src/tests/main.py -s
  test-custom:
    <<: *build
    <<: *env
    <<: *test
    command: pytest /app/src/tests/custom.py -s