name: deploy

on:
  push:
    branches:
      - production
      - main
jobs:
  deploy-py-server-argo:
    name: Deploy PY server Argo
    uses: ./.github/workflows/helpers-deploy-argo.yaml
    secrets:
      KITTL_CI_APP_PRIVATE_KEY: ${{ secrets.KITTL_CI_APP_PRIVATE_KEY }}
      ECR_ROLE_ARN: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_ECR_ROLE_ARN || secrets.STAGING_ECR_ROLE_ARN }}
