name: deploy
on:
  push:
#    branches:
#      - production
#      - main
jobs:
  deploy-py-server-argo:
    name: Deploy PY server Argo
    uses: ./.github/workflows/helpers-deploy-argo.yaml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
