name: publish
on:
  push:
    branches:
      - production
      - main
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the Docker image
        run: |
          docker build . --tag ghcr.io/kittl/vectorizing:${{ github.ref_name }}
          docker run ghcr.io/kittl/vectorizing:${{ github.ref_name }}
          docker push ghcr.io/kittl/vectorizing:${{ github.ref_name }}